version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${ui_version}
    ports:
      - ${port}:${port}/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${post_version}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAME}/comment:${comment_version}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:

